### ISSUE TITLE
Bug in running univariate fine mapping

### ISSUE THREAD

**Issue by rfeng2023** [cumc/xqtl-protocol#1026]
There is a bug when I am trying to run mnm_regression.ipynb, which works well at the end of July. I did not see obvious update in recent modification in that pipeline, could be some updates in pecotmr?
> Dimension of input genotype data is 806 rows and 19076 columns for genomic region of chr17:42560179-46679816
> Follow-up on region because signals above PIP threshold 0.025 were detected in initial model screening.
> Total time elapsed for susie_wrapper: 4.362
> Number of variants dropped: 8653 out of 19076 total variants.
> Total time elapsed for susie_wrapper: 0.410000000000004
> Type of analysis performed: st-blr-individual-level-dense-ld
> Type of analysis performed: st-blr-individual-level-dense-ld
> Randomly selecting 5000 out of 5000 input variants for cross validation purpose.
> Error in (function (.x, .f, ..., .progress = FALSE)  : ℹ In index: 1.
> Caused by error in `` `*tmp*`[, i] ``:
> ! subscript out of bounds
> Calls: lapply ... resolve.list -> signalConditionsASAP -> signalConditions
> Execution halted

**Comment by gaow** [comment]
oh boy, this is the cross validation for TWAS which underwent some changes as @Chunmingl works on the multivariate version. 

I think we need a MWE for this -- could you save the data in question using --save-data option and also extract the code from the log file that reproduce the issue, then we communicate it on slack with Chunming?
