### ISSUE TITLE
TensorQTL indices possible bug

### ISSUE THREAD

**Issue by minqiao** [cumc/xqtl-protocol#998]
When submitting jobs using TensorQTL.ipynb, there is either KeyError or ValueError. I changed the following indices

        pairs_df.columns.values[7]  = "pvalue"
        pairs_df.columns.values[8]  = "beta"
        pairs_df.columns.values[9]  = "se"

to

        pairs_df.columns.values[6]  = "pvalue"
        pairs_df.columns.values[7]  = "beta"
        pairs_df.columns.values[8]  = "se"
        
in [cis_1], it went through smoothly without raising errors.

**Comment by gaow** [comment]
Thanks @minqiao . @grennfp could you take a look and verify it on your end with some test data and fix it as necessary? @Bale4 this has to do with the sQTL bug?
